sudo: required
services:
    - docker

before_install:
    - docker build -t xenonpluton/docker-react -f Dockerfile.dev .

    script: 
        - docker run -e CI=true xenonpluton/docker-react npm run test
