language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t xenonpluton/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true xenonpluton/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "DockerOhio"
    env: "Dockerohio-env"
    bucket_name: "elasticbeanstalk-us-east-2-867256822293"
    bucket_path: "DockerOhio"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

